### ISSUE TITLE
Výběr kategorie pro kartu

### ISSUE THREAD

**Issue by krizovj** [LIBCAS/INDIHU-Mind#1]
Když chci přiřadit ke kartě kategorii, rozbalí se seznam kategorií, které jsou všechny na stejné úrovni. Bylo by možné, aby u toho výběru byla naznačena struktura kategorií (strom)?

**Comment by nnis** [comment]
K výběru kategorií mě napadá, že nemohu přímo ve výběru kategorie přidat novou, ale musím vybrat z již existujících. To znamená, že prvním krokem je založit kategorii a ne kartu, pokud je chci sdružovat. Navrhuji přidat ještě políčko "Přidat novou". Totéž platí i pro štítek. 

![kategorie](https://user-images.githubusercontent.com/15922183/58631926-4f885580-82e4-11e9-9e75-e35a02258aa8.png)

**Comment by karel947** [comment]
@nnis Chování select boxu jsme upravili takto: Jakmile není daný text (název kategorie) vytvořený v sytému, zobrazí se možnost "Vytvořit <jméno kategorie> viz příloha, po kliknutí na tento text se zobrazí okno Vytvořit kategorii/štítek . Chování upraveno jak pro Kategorie, tak i pro Štítky.
![image](https://user-images.githubusercontent.com/12020277/59424584-88d8bf00-8dd4-11e9-8f54-6c3027b59a22.png)

**Comment by karel947** [comment]
@krizovj V otázce stromové struktury máme dvě možnosti:
1) Mít stromovou strukturu, pak nebude fungovat filtrování
2) Filtrování (aktuální chování), ale bez stromové struktury
V případě kombinace by byla implementace náročná a přidaná hodnota uživateli sporná. Problém by nastal především v případech kdy hledaný text obsahuje jak název kategorie, tak i název jejich podkategorií - byl by ve výpisu (vysunovacím okně) celý strom, část stromu, i když některé "mezi" kategorie neobsaují daný výraz?

**Comment by rudky4** [comment]
V rámci možnosti optimalizované, ukážka bola prezentovaná na stretnutí.
