### ISSUE TITLE
Šablony

### ISSUE THREAD

**Issue by jpolisensky** [LIBCAS/INDIHU-Mind#10]
Jak bude fungovat šablona? V současné době lze v šabloně pouze vytvářet atributy ale ani ty nemají pole pro „hodnotu“. Předpokládám, že bych měl mít možnost si vytvořit šablony pro typy nejvíce používaných karet a pak je jen plnit daty včetně názvu, popisu (obsahu), kategorií atd. Tak to ale v současné době nefunguje.

**Comment by rudky4** [comment]
Aktuálne šablóna obsahuje len "kostru" a teda rozsah atribútov karty. 
Konkrétny obsah sa má vytvárať až v danej inštancii po vytvorení karty. 
Prediskutujeme na spoločnom stretnutí.
