### ISSUE TITLE
Jedinečný identifikátor

### ISSUE THREAD

**Issue by jpolisensky** [LIBCAS/INDIHU-Mind#11]
Bude se generovat systémový jedinečný identifikátor (např. UUID?) pro každou kartu?

**Comment by rudky4** [comment]
Identifikátor už je generovaný, zabezpečíme jeho zobrazovanie.
Na diskusiu: Nebol by vhodnejší jednoduchší identifikátor (číslo, vzostupná rada?)

**Comment by motyc** [comment]
Nejlepší by bylo unikátní URI

**Comment by motyc** [comment]
UUID je skvělé, ale jak jsem psal, zobrazoval bych jej jako celou URL, nikoli jen jako fragment. Tj. místo:
`ID: 1ac150bf-4ba0-4bb8-a31c-f17fd90b1679`
ukazovat: `https://mind.indihu.cz/card/1ac150bf-4ba0-4bb8-a31c-f17fd90b1679` (tlačítko zkopírovat pak bude kopírovat tuto URL).

**Comment by motyc** [comment]
Teď koukám, že pro danou věc je samostané issue #72, zde lze zavřít.
