### ISSUE TITLE
Práce s více kartami

### ISSUE THREAD

**Issue by jpolisensky** [LIBCAS/INDIHU-Mind#12]
Měla by být možnost pracovat současně se dvěma i více kartami, doplňovat je, propojovat apod. Před zavřením aplikace nebo PC by se měl objevit dotaz „Vytvořit (uložit) kartu?“

**Comment by rudky4** [comment]
Prepojovanie kariet je podporované. Pracovať s viacerými kartami je možné v samostatných oknách prehliadača. Upozornenie na neuložené zmeny doplníme.

**Comment by rudky4** [comment]
Pridat ikonu na otvorenie v novom okne.
