### ISSUE TITLE
Přílohy

### ISSUE THREAD

**Issue by jpolisensky** [LIBCAS/INDIHU-Mind#13]
Bude možné stahovat přílohy jako např. obrázky videa apod. přímo z internetu?

**Comment by rudky4** [comment]
U obrázkov si to viem prestaviť (na základe linku sa stiahne súbor do aplikácie), u videa to nebude možné (tam je vhodné pridať len link do popisu karty ako odkaz).

**Comment by rudky4** [comment]
Pripravené na test, kedy sa do INDIHU Mind importuje odkaz na dokument z Internetu.

![image](https://user-images.githubusercontent.com/7311447/95837332-c9d24200-0d40-11eb-9c2d-8f274d6b3eed.png)
