### ISSUE TITLE
Klíčová slova

### ISSUE THREAD

**Issue by jpolisensky** [LIBCAS/INDIHU-Mind#16]
Bude nutné oddělovat klíčová slova specifickým symbolem (např. středníkem)?

**Comment by yantom** [comment]
Obsah jakéhokoliv atributu textového typu (tedy i obsah Vámi vytvořeného atributu klíčová slova) je zaindexován jako souvislý text a takto je atribut i prohledáván při fulltextovém vyhledávání. Způsob oddělení klíčových slov je tedy prozatím libovolný, systém totiž rozdělení neprovádí.

Pokud je při vyhledávání zadáno jedno slovo, jsou nalezeny všechny karty které takové slovo obsahují v některém textovém atributu.
Pokud je při vyhledávání zadáno více slov (fráze), musí se tyto v stejném pořadí a v nízké vzdálenosti mezi sebou vyskytovat v textovém atributu.

**Comment by jpolisensky** [comment]
Dobrý den,
 
je "Popis" (obsah karty, excerpovaný text) také chápán jako atribut a je možné v něm fulltextově vyhledávat?
 
J. Polišenský
 
______________________________________________________________
> Od: "Jan Tomášek" <notifications@github.com>
> Komu: "LIBCAS/INDIHU-Mind" <INDIHU-Mind@noreply.github.com>
> Datum: 02.01.2020 16:12
> Předmět: Re: [LIBCAS/INDIHU-Mind] Klíčová slova (#16)
>
Obsah jakéhokoliv atributu textového typu (tedy i obsah Vámi vytvořeného atributu klíčová slova) je zaindexován jako souvislý text a takto je atribut i prohledáván při fulltextovém vyhledávání.
Pokud je při vyhledávání zadáno jedno slovo, jsou nalezeny všechny karty které takové slovo obsahují v některém textovém atributu.
 Pokud je při vyhledávání zadáno více slov (fráze), musí se tyto v stejném pořadí a v nízké vzdálenosti mezi sebou vyskytovat v textovém atributu. Nelze tedy zadat textový atrubut o délce 20 slov a ve fulltextovém vyhledávání nalézt příslušnou kartu zadáním prvního a posledního slova.

**Comment by yantom** [comment]
Popis není atribut ale při fulltextovém vyhledávání karet je prohledáván
stejným způsobem jako textové atributy.

Narozdíl od atributů není popis verzovaný, tedy při úpravě popisu nevzniká
nová verze obsahu.

**Comment by rudky4** [comment]
Diskutované na poslednom jednaní, doporučujeme vytvoriť samostatné pole karty, kde je možné _klíčová slova_ vložiť.
V prípade obecnejšej potreby môže byť vytvorený dedikovaný atribút, ktorý bude na každej karte. Nateraz uzavreté.
