### ISSUE TITLE
Karta popis

### ISSUE THREAD

**Issue by jpolisensky** [LIBCAS/INDIHU-Mind#19]
Na kartu do části "Popis" nelze zkopírovat obrázek.

**Comment by jirkacechak** [comment]
obrázek lze ke kartě přidat jako přílohu

**Comment by jpolisensky** [comment]
Soubor s obrázkem se stáhne nejprve do Dokumentů, pak jej mohu přidat ke kartě. Je to ale odkaz a pokud chci obrázek vidět musím si ho stáhnout a tím se mi otevře v úplně jiném okně, takže současně nevidím jak kartu tak obrázek. Původně jsem doufal, že bude možné obrázek, nebo alespoň náhled vidět přímo na kartě. V Dokumentech jsem ho nechtě uložil dvakrát a nelze ho jednou smazat.
 
Polišenský
______________________________________________________________
> Od: "Jiří Čechák" <notifications@github.com>
> Komu: "LIBCAS/INDIHU-Mind" <INDIHU-Mind@noreply.github.com>
> Datum: 09.09.2020 11:34
> Předmět: Re: [LIBCAS/INDIHU-Mind] Karta popis (#19)
>
 
obrázek lze ke kartě přidat jako přílohu
