### ISSUE TITLE
Přidat soubor z počítače

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Mind#2]
Pokud se nemýlím, mohu přidat jen soubor online nebo z drivu, dropboxu, ale ne z počítače. 

![pridat-soubor-pocitac](https://user-images.githubusercontent.com/15922183/58632017-aee66580-82e4-11e9-8f9c-5647c66d440a.png)

**Comment by rudky4** [comment]
@nnis s možnosťou pridávania obsahu priamo z PC v budúcnosti počítame. 
Predtým však musíme prediskutovať obmedzenia na typy súborov, veľkosť, celkovú kapacitu úložiska a pod. Tieto súbory budú ukladané priamo na serveroch prevádzkovateľa, čo je jemné riziko navyše.

**Comment by nnis** [comment]
Rozumím, díky za vysvětlení

**Comment by rudky4** [comment]
Funkcionalita implementovaná.
