### ISSUE TITLE
Grafické řešení levého menu

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Mind#21]
1) Vertikální scrollbar řešit graficky decentněji
2) Lépe opticky oddělit dílčí položky
3) Zbytečně velké písmo - menší písmo, ale verzálkami/tučně?
4) Umožnit posuvem dynamicky nastavit šířku menu

Celkově ne úplně přehledné, zbytečně nevyužité místo v horní části (obří tlačítko "Nová karta" a hodně místa kolem)...

**Comment by rudky4** [comment]
1,2,3 vyriešené
4 aktuálne nebudeme implementovať, ide o pracnejšiu záležitosť.

(poznámka, opravená bude ešte drobnosť s viditeľnosťou tlačítka Nová karta)
