### ISSUE TITLE
Vyhledávací pole dnamicky

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Mind#26]
Všechna pole pro vyhledávání (propojování karet, hlavní vyhledávání...) by měla fungovat s dynamickým našeptáváním, aby uživatel měl jasnější odezvu.

**Comment by rudky4** [comment]
Všetky pole (až na obecný search) už obsahujú autofill.
Issue uzatváram a prosím prípadne o konkrétne pripomienky k jednotlivým elementom.
