### ISSUE TITLE
Přehled karet - editace karty/přejít na detail

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Mind#3]
Editace karty je až úplně vpravo, je to strašně daleko a nefunguje dvojklik na název karty. Možná bych tu editaci dala někam blíž k názvu. Navíc se možnost smazání a editace objeví jen po najetí myší a až po kliknutí se pak zobrazí nabídka akcí, což editaci vytvořené karty prodlužuje. 
Po kliknutí na kartu také není klikací kategorie, což by podle mě mohla být, protože to je nějaký způsob filtrování. 
![editace-kartypng](https://user-images.githubusercontent.com/15922183/58632368-962a7f80-82e5-11e9-816f-3ddbe360775f.png)

**Comment by karel947** [comment]
@nnis  Tlačítka jsou teď viditelná vždy. Tlačítka byla přesunuta vpravo od názvu karty. Kategorii jsme změnili, aby byla v detailu klikatelná - po kliknutí je uživatel přesměrován na "přehled karet" v dané kategorii. Dále se v levém menu nastaví daná kategorie jako aktuální. 
Prakticky kliknutí na kategorii u karty vyvolá stejné chování jako kliknutí na kategorie v levém menu.
