### ISSUE TITLE
Při kliknutí na "Nová karta" zohledňovat, kde jsem

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Mind#33]
Do kategorie přednastavit tu právě aktivní.

**Comment by tomas-myslik** [comment]
Po kliknutí na nová karta se nyní bere v potaz, ve které kategorii uživatel právě je a ta se přednastaví jako zvolená kategorie.

**Comment by motyc** [comment]
Nefunkční - pokud kartu nevytvářím z rootu, skončím jen s bílou obrazovkou.

**Comment by motyc** [comment]
Stále totéž.
