### ISSUE TITLE
Výpis 

### ISSUE THREAD

**Issue by nnis** [LIBCAS/INDIHU-Mind#4]
Asi po vytvoření karty jsem se dostala na tento výpis. Nejdřív jsem nevěděla, jak se na něj dostat, ale je to detail karty a tam bych asi čekala něco jiného, že už jsem uvnitř nebo víc informací o kartě nebo už rozbalenou nabídku dalších akcí. Nějak zkrátka úplně nevím, k čemu tento krok slouží. 
![vypis](https://user-images.githubusercontent.com/15922183/58632439-bb1ef280-82e5-11e9-8aba-6a100f2043ac.png)

**Comment by krizovj** [comment]
Tohle mě taky zmátlo...

**Comment by rudky4** [comment]
Na základe diskusii boli zapracované úpravy výpisu a zobrazenia.
