### ISSUE TITLE
Karta - ukládání

### ISSUE THREAD

**Issue by jpolisensky** [LIBCAS/INDIHU-Mind#42]
Pokud mám rozpracovanou novou kartu a před jejím uložením kliknu mimo její pole, pak se vymaže vše co jsem vložil na kartu. Před tím by mělo vyskočit varovné okno s doporučením: „Uložte kartu, nebo uložené informace budou smazány.“ Nebo jinak zachovat vložené informace.

**Comment by tomas-myslik** [comment]
Nyní se před zavřením formuláře zobrazí potvrzovací okno, po jeho potvrzení dojde k zavření obou oken.

**Comment by motyc** [comment]
Potvrzuji. K zavření.
