### ISSUE TITLE
Šablona karty

### ISSUE THREAD

**Issue by jpolisensky** [LIBCAS/INDIHU-Mind#44]
Většina předdefinovaných atributů v šabloně jsou povinné. Mělo by být možné použít šablonu a nemuset vyplnit všechny předdefinované atributy.

**Comment by jirkacechak** [comment]
při vytváření karty a zvolení šablony, je možné atributy odstranit, a pak je nebude nutné vyplňovat

**Comment by jpolisensky** [comment]
Zkusil jsem vyvořit novou kartu ze šablony, kde jsem umazal některé atributy. Ostatní jsem jakoby vyplnil. Kartu se však nepodařilo vytvořit, zobrazila se hláška, že se stala chyba, abych to zkusil znovu. Ani pak jsem ale nebyl úspěšný. Bylo by užitěčné, pokud by aplikace indikovala, kde k chybě došlo.  
Polišenský
______________________________________________________________
> Od: "Jiří Čechák" <notifications@github.com>
> Komu: "LIBCAS/INDIHU-Mind" <INDIHU-Mind@noreply.github.com>
> Datum: 10.09.2020 14:46
> Předmět: Re: [LIBCAS/INDIHU-Mind] Šablona karty (#44)
>
 
při vytváření karty a zvolení šablony, je možné atributy odstranit, a pak je nebude nutné vyplňovat

**Comment by motyc** [comment]
Za mne již v pořádku - jde zavřít.
