### ISSUE TITLE
Vytvorenie 1. kategorie

### ISSUE THREAD

**Issue by rudky4** [LIBCAS/INDIHU-Mind#5]
Pokiaľ nie je vytvorená žiadna kategória, nie je možné na prehľade https://indihumind.inqool.cz/categories vytvoriť novú. 
Prosím o pridanie tlačíka (aktulne je možne vytvoriť kategóriu len cez levé menu).

**Comment by karel947** [comment]
@rudky4 Opravno a otestováno
