### ISSUE TITLE
Test instalace API

### ISSUE THREAD

**Issue by mduda100871** [LIBCAS/INDIHU-Mind#53]
Zdravím,

mám zkompilované, nainstalované a běžící API.

Před prvním spuštěním jsem přetížil proměnnou `env` v souboru `application.properties` nastavením na hodnotu `env=staging` abych měl k dispozici nějaká data k otestování.

Aplikace po prvním spuštění provedla incializaci jader v Solru a vytvoření tabulek v příslušné databázi. Všechno bez problému proběhlo.

Nyní bych rád provedl základní test - ověření přihlášení přes `/api/login` a tady nejsem schopen se pohnout z místa.

Není mi úplně jasné, jaké uživatelské jméno a heslo mám použít. Když provedu dotaz do tabulky `SELECT * FROM vzb.vzb_user;`, dostanu následující výpis:

![vzb_user-00](https://user-images.githubusercontent.com/8750622/96253135-5c7a1780-0fb3-11eb-9ba2-9af60aa64a1f.png)

Mám pro otestování vzít odtud nějakého uživatele? Pokud ano, co je uživatelské jméno? Email nebo id? A jak zjistím vygenerované heslo vniklé při první inicializaci? 

Nebo mám vzít ten base64 zakódovaný řetězec z proměnné `security.jwt.secret`? Ten jsem vytvořil příkazem:
`$ echo "jmeno:heslo" | base64`

Test jsem pak zkusil pomocí Postmanu, ale ve všech případech bez úspěchu.

Jaký je tedy správný postup?

Díky, MD

**Comment by rudky4** [comment]
Upresnené na wiki https://github.com/LIBCAS/INDIHU-Mind/wiki/Build-&-Deploy a zaslané i do mailu.

**Comment by mduda100871** [comment]
Potvrzuji funkční stav:

`curl -X POST 'https://indihu-mind.lib.cas.cz/api/login' -H "accept: */*" -H  "Authorization: Basic XXXXX" -d ""`

![indihu-mind-login-00](https://user-images.githubusercontent.com/8750622/96553976-3b1c7280-12b6-11eb-95d4-6ffb6a2576fd.png)

MD
