### ISSUE TITLE
V detailu karty neni zobrazen Popis

### ISSUE THREAD

**Issue by rudky4** [LIBCAS/INDIHU-Mind#6]
Pri editaci je Popis viditelny:
![image](https://user-images.githubusercontent.com/7311447/59088982-524d0100-8909-11e9-8a41-e2dc4cdc36ca.png)

V detailnu neni zobrazen:
![image](https://user-images.githubusercontent.com/7311447/59089003-5c6eff80-8909-11e9-8864-38a66c6f1c68.png)

**Comment by karel947** [comment]
Implementováno.
