### ISSUE TITLE
Subkategorie

### ISSUE THREAD

**Issue by jpolisensky** [LIBCAS/INDIHU-Mind#7]
Jak se tvoří subkategorie?

**Comment by rudky4** [comment]
Najprv je potrebné v "strome" kategórií v ľavej časti vybrať kategóriu (dostať sa do nej) a následne klik na "Vytvořit novou”. 
Vyskočí popup kde si môžete overiť či sa nová subkategória vytvorí na správnom mieste.

![image](https://user-images.githubusercontent.com/7311447/70847655-05715680-1e67-11ea-91c6-0dc250cfa2e5.png)

**Comment by rudky4** [comment]
Vyriešiť intuitívnosť, plusko vedľa kategórie
