### ISSUE TITLE
Vůbec nefunguje tlačítko "stáhnout přílohu" u karty

### ISSUE THREAD

**Issue by motyc** [LIBCAS/INDIHU-Mind#78]

**Comment by adamradvan** [comment]
Prosíme o pretestovanie, nahrajte nový súbor, pripojte ho na kartu a pokúste sa stiahnuť prílohu (tento novo-nahratý súbor).

Prílohy sa vám zrejme nepodarilo stiahnuť pri entitách ktoré "staré", resp. boli vytvorené pred migráciou z nášho dev cloudu. Pri migrácii sa presúvala iba databáza a nie súbory z filesystému. Kvůli tomu zatiaľ v aplikácií existujú "ghost" dokumenty, pre ktoré existujú síce databázové entity, ale neexistujú súbory ktoré by išlo stiahnuť. 

Ide o neštandardnú situáciu a preto potrebujeme jasné zadanie ako sa s "ghost" entitami popasovať. Vieme bud my vytvoriť endpoint na premazanie ktorý prevolá administrátor a potom ho aj zmažeme keďže by nemala uź nastať takáto situácia. Alebo to necháme na starosti aby sa s tým popasoval administrátor manuálne.

**Comment by motyc** [comment]
Otestováno a s novým souborem funguje. Za mne není třeba zpětně řešit, byla tam pouze testovací data.
