### ISSUE TITLE
Pořadí atributů

### ISSUE THREAD

**Issue by jpolisensky** [LIBCAS/INDIHU-Mind#8]
Je možné změnit pořadí již vytvořených atributů?

**Comment by rudky4** [comment]
Aktuálne táto funkcionalita nie je podporovaná, aplikáciu môžeme rozšíriť.

**Comment by motyc** [comment]
Chtěl jsem otestovat, ale nikde to nevidím. Jak to má fungovat?

**Comment by rudky4** [comment]
V detailu karty @motyc 
![image](https://user-images.githubusercontent.com/7311447/109174302-039e6500-7785-11eb-90c8-6633c4df2510.png)

**Comment by motyc** [comment]
V pořádku, už to mám.
