### ISSUE TITLE
Oprava logback.xml

### ISSUE THREAD

**Issue by mduda100871** [LIBCAS/INDIHU-Mind#81]
Zdravím,

je potřeba opravit/změnit konfiguraci logování. Konkrétně:

![logback-00](https://user-images.githubusercontent.com/8750622/101759328-be4d8e00-3ad9-11eb-9696-ed67d5b1b4b2.png)

kde je prefix logu `arclib`, což je matoucí, správně má být něco jako `mind` apod.

Vyskytuje se to tam několikrát i dále.

MD

**Comment by adamradvan** [comment]
Dobrý deň,

okrem fixu pre issue sa nam podarilo vytvoriť logovanie podľa prihláseného usera, veríme, že to zlepší debugovanie.
Po novom sa bude okrem bežných log files tvoriť aj folder `user_logs/` kde sa budú tvoriť logfiles odpovedújce prihláseným používateľom.
