### ISSUE TITLE
Bibliografické informace

### ISSUE THREAD

**Issue by jpolisensky** [LIBCAS/INDIHU-Mind#9]
Každá karta by měla obsahovat bibliografické informace, nebo informace o zdroji, s výjimkou karet s vlastním textem. Tyto informace by měly být propojeny s Registrem literatury (zdrojů). Tyto informace by asi neměly být atributem nebo kategorií.

**Comment by rudky4** [comment]
Táto funkcionalita je vo vývoji, do konca roka počítame s nasadením testovacej verzie na pripomienkovanie.
